"""Render the alert store as a single self-contained web page.

Design principle 4 says deliver where people already are, and principle 3 says
alerts must be actionable. A map is neither on its own — it is the thing someone
opens *after* an email, to decide whether a detection is worth a trip. That is
the job this page has to do well, and it is a different job from looking good.

Four things follow from it directly:

* **A list, not only pins.** Fifteen markers on satellite imagery cannot be
  scanned, sorted or counted by eye. The list is the part that makes this a tool.
* **Place names.** Esri's imagery carries no labels, so a bare pin cannot answer
  "where is this?" — the first question anyone asks. A reference overlay and a
  topographic basemap both answer it.
* **The monitored area, drawn.** Recall is 0.32 and coverage is one taluk, so a
  blank area can mean "nothing found", "not looked at closely enough", or "not
  monitored at all". Drawing the boundary separates the third from the others.
* **A download.** A forest officer wants coordinates in their GPS, not in a
  browser tab.
* **Every marker legible.** Pending detections were once drawn as faint
  hollow rings. Every alert is pending until a second pass confirms it, so
  that styling made the entire map nearly invisible. Status is now carried
  by a halo on the confirmed ones instead of by fading the rest.

**Why not PMTiles.** The plan specified precomputed vector tiles. At this scale
that is engineering for a size that does not exist: the whole dataset inlines at
a few tens of kilobytes with no tile server and no second file to fall out of
sync. Revisit if the AOI grows a hundredfold.

**Why accuracy is on the page rather than in a footnote.** Roughly one in five
markers is wrong and two thirds of real clearing is missing. Someone who does
not know that will over-trust the pins and, worse, read empty space as safe.

The wording is deliberate throughout: *possible disturbance, requires ground
verification*. Never "illegal logging" — a model output is not evidence of a
crime, and the people most likely to be accused are rarely the people with the
means to contest it.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

__all__ = ["build_page", "meeting_current_config", "write_page"]

# Esri's free services. Attribution is a condition of use, not a courtesy.
_IMAGERY = (
    "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"
)
_TOPO = (
    "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}"
)
_LABELS = "https://server.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer/tile/{z}/{y}/{x}"
_ATTRIBUTION = (
    "Imagery &copy; Esri, Maxar, Earthstar Geographics &middot; "
    "Detections from Sentinel-2 and AlphaEarth via Google Earth Engine"
)

# Everything dynamic travels in one JSON object swapped in for this token. The
# alternative — str.format over the whole document — would mean doubling every
# CSS brace and would collide with JavaScript template literals, which is a lot
# of fragile escaping to save one substitution.
_CONFIG_TOKEN = "__VANACHAKSHU_CONFIG__"


def _as_js(value: Any) -> str:
    """Serialise a value for embedding inside a ``<script>`` element.

    ``json.dumps`` alone is **not** safe here. It escapes quotes but leaves
    ``<`` alone, so a property containing ``</script>`` ends the script element
    early and everything after it is parsed as markup — the classic way an
    inlined-JSON page becomes an injection vector.

    The alert data is generated by this pipeline rather than submitted by
    anyone, so nothing hostile is expected in it. That is a reason the bug would
    go unnoticed, not a reason it is safe: place names and future fields flow
    into this page, and the page is published.

    Escaping the angle brackets as ``\\u003c`` keeps the value identical after
    ``JSON.parse``. The line separators are escaped because they are valid in
    JSON but terminate a JavaScript string literal.
    """
    return (
        json.dumps(value, separators=(",", ":"))
        .replace("<", "\\u003c")
        .replace(">", "\\u003e")
        # Written as escapes rather than literals: the raw characters are
        # invisible in an editor, which is exactly how they survive review.
        .replace("\u2028", "\\u2028")
        .replace("\u2029", "\\u2029")
    )


def meeting_current_config(geojson: dict[str, Any], min_area_ha: float) -> dict[str, Any]:
    """Drop detections the current configuration would no longer produce.

    The alert store accumulates across runs, so it outlives the settings that
    filled it. When ``min_clearing_ha`` moved from 0.05 to 0.20 — a change that
    took measured precision from 0.31 to 0.80 — **42 of the 57 stored alerts
    were below the new floor**. Publishing them beside a claim of 0.80 precision
    overstated accuracy on three quarters of the map.

    Filtering here rather than pruning the store is deliberate: the store keeps
    its full history, and the page shows only what today's detector stands
    behind.
    """
    kept = [
        f
        for f in geojson.get("features", [])
        if float(f.get("properties", {}).get("area_ha") or 0.0) >= min_area_ha
    ]
    return {**geojson, "features": kept}


def compared_period(geojson: dict[str, Any]) -> str | None:
    """Which years of imagery the published detections were made from.

    Read out of the detections rather than from the calendar. An earlier version
    computed this from today's date and displayed **"2025→2026" for detections
    actually made from 2024 and 2025 imagery** — AlphaEarth is annual and
    published months in arrears, so the current year is never the compared year.
    On a page whose whole purpose is to be honest about its limits, inventing
    the data's date is close to the worst small lie available.

    Returns ``None`` when the detections do not record it, which is true of
    every alert written before the field existed. The page then shows its build
    date instead, clearly labelled as such. Showing nothing is better than
    showing a plausible wrong year, because a wrong year is not obviously wrong.
    """
    years: list[tuple[int, int]] = [
        (int(b), int(r))
        for f in geojson.get("features", [])
        if (b := f.get("properties", {}).get("baseline_year")) is not None
        and (r := f.get("properties", {}).get("recent_year")) is not None
    ]
    if not years:
        return None

    # Span the whole set: a store filled over several cycles can hold more than
    # one year-pair, and quoting only the newest would overstate how current the
    # older markers are.
    return f"{min(b for b, _ in years)}\u2013{max(r for _, r in years)}"


_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Vanachakshu &mdash; possible forest disturbance</title>
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Ccircle cx='16' cy='16' r='15' fill='%23166534'/%3E%3Ccircle cx='16' cy='16' r='5.5' fill='%23f8fafc'/%3E%3C/svg%3E">
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css">
<style>
  :root {
    --paper:#ffffff; --sunk:#f4f6f4; --line:#e2e6e2; --line-soft:#eef1ee;
    --ink:#14181a; --ink-2:#3d4a44; --muted:#66736c;
    --brand:#166534; --brand-soft:#eaf3ed;
    --confirmed:#be123c; --pending:#c2660a; --focus:#1d4ed8;
    --pad:18px;
  }
  * { box-sizing:border-box; }
  html,body { margin:0; height:100%; background:var(--paper); color:var(--ink);
    font:15px/1.5 ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;
    -webkit-font-smoothing:antialiased; }
  button,select { font:inherit; color:inherit; }

  .app { display:flex; height:100%; }
  .sidebar { width:392px; flex:none; background:var(--paper);
    border-right:1px solid var(--line); display:flex; flex-direction:column; min-height:0; }
  .mapwrap { flex:1; position:relative; min-width:0; }
  #map { position:absolute; inset:0; background:#0f1613; }

  .head { padding:var(--pad) var(--pad) 14px; }
  .head h1 { margin:0; font-size:21px; font-weight:650; letter-spacing:-.025em;
    display:flex; align-items:center; gap:9px; }
  .head h1 svg { flex:none; }
  .head .sub { color:var(--muted); font-size:13px; margin-top:3px; }

  .warn { margin:0 var(--pad); background:#fff8ed; border:1px solid #f6dfbc;
    border-radius:8px; padding:10px 12px; font-size:12.5px; line-height:1.5;
    color:#7a4c07; }
  .warn strong { color:#653f05; }

  .figures { display:flex; gap:26px; padding:16px var(--pad) 4px; }
  .fig b { display:block; font-size:30px; font-weight:640; line-height:1;
    letter-spacing:-.03em; font-variant-numeric:tabular-nums; }
  .fig span { display:block; color:var(--muted); font-size:11px; font-weight:600;
    text-transform:uppercase; letter-spacing:.07em; margin-top:5px; }
  .period { padding:8px var(--pad) 0; color:var(--muted); font-size:12px; }

  .controls { padding:14px var(--pad); display:flex; gap:8px; align-items:center; }
  .seg { display:flex; background:var(--sunk); border-radius:8px; padding:3px; flex:1;
    gap:2px; }
  .seg button { flex:1; background:none; border:0; padding:6px 2px; font-size:12px;
    font-weight:550; color:var(--muted); cursor:pointer; border-radius:6px;
    white-space:nowrap; }
  .seg button:hover { color:var(--ink); }
  .seg button[aria-pressed="true"] { background:var(--paper); color:var(--ink);
    box-shadow:0 1px 2px rgba(0,0,0,.09); }
  .seg button .n { opacity:.55; font-variant-numeric:tabular-nums; }
  select { background:var(--paper); border:1px solid var(--line); border-radius:8px;
    padding:7px 8px; font-size:12px; cursor:pointer; color:var(--ink-2); }

  .key { display:flex; flex-wrap:wrap; gap:6px 16px; padding:0 var(--pad) 14px;
    font-size:11.5px; color:var(--muted); }
  .key span { display:flex; align-items:center; gap:6px; }
  .key i { width:11px; height:11px; border-radius:50%; flex:none;
    border:1.5px solid var(--paper); box-shadow:0 0 0 1px rgba(0,0,0,.18); }
  .key .ring { box-shadow:0 0 0 1px rgba(0,0,0,.18), 0 0 0 3.5px rgba(190,18,60,.32); }
  .key .box { width:14px; height:9px; border-radius:2px; border:1.5px dashed #16a34a;
    background:none; box-shadow:none; }

  .listwrap { flex:1; overflow-y:auto; min-height:0; border-top:1px solid var(--line); }
  .row { display:flex; gap:11px; align-items:flex-start; width:100%; text-align:left;
    background:none; border:0; border-bottom:1px solid var(--line-soft);
    padding:11px var(--pad); cursor:pointer; }
  .row:hover { background:var(--sunk); }
  .row[aria-current="true"] { background:var(--brand-soft);
    box-shadow:inset 3px 0 0 var(--brand); }
  .row:focus-visible { outline:2px solid var(--focus); outline-offset:-2px; }
  .pip { flex:none; width:11px; height:11px; border-radius:50%; margin-top:5px;
    box-shadow:0 0 0 1px rgba(0,0,0,.15); }
  .pip.c { background:var(--confirmed);
    box-shadow:0 0 0 1px rgba(0,0,0,.15), 0 0 0 3.5px rgba(190,18,60,.28); }
  .pip.u { background:var(--pending); }
  .main { flex:1; min-width:0; }
  .top { display:flex; align-items:baseline; justify-content:space-between; gap:8px; }
  .ha { font-variant-numeric:tabular-nums; font-weight:620; font-size:14.5px; }
  .badge { font-size:10px; font-weight:650; text-transform:uppercase;
    letter-spacing:.05em; padding:2px 6px; border-radius:20px; white-space:nowrap; }
  .badge.c { background:#fee7ec; color:var(--confirmed); }
  .badge.u { background:#fdf0e0; color:var(--pending); }
  .meta { display:block; color:var(--muted); font-size:11.5px; margin-top:2px;
    font-variant-numeric:tabular-nums; white-space:nowrap; overflow:hidden;
    text-overflow:ellipsis; }
  .empty { padding:22px var(--pad); color:var(--muted); font-size:13px; line-height:1.6; }

  .foot { border-top:1px solid var(--line); padding:14px var(--pad) var(--pad);
    background:var(--sunk); }
  .dl { width:100%; background:var(--paper); border:1px solid var(--line);
    border-radius:8px; padding:10px; cursor:pointer; font-size:13px; font-weight:550;
    margin-bottom:12px; box-shadow:0 1px 2px rgba(0,0,0,.05); }
  .dl:hover { border-color:var(--brand); color:var(--brand); }
  details { font-size:12.5px; color:var(--ink-2); border-top:1px solid var(--line);
    padding-top:10px; margin-top:10px; }
  details:first-of-type { border-top:0; margin-top:0; padding-top:0; }
  summary { cursor:pointer; color:var(--ink); font-size:12.5px; font-weight:600; }
  details p { margin:9px 0; line-height:1.55; }
  a { color:var(--brand); }

  .toggle { display:none; }

  .leaflet-popup-content-wrapper { background:var(--paper); color:var(--ink);
    border-radius:10px; box-shadow:0 4px 20px rgba(0,0,0,.3); }
  .leaflet-popup-content { margin:14px 16px; font-size:13px; }
  .leaflet-popup-content h3 { margin:0 0 8px; font-size:14px; font-weight:640; }
  .leaflet-popup-content table { border-collapse:collapse; margin:8px 0; }
  .leaflet-popup-content td { padding:2px 14px 2px 0; }
  .leaflet-popup-content td:first-child { color:var(--muted); }
  .leaflet-popup-content .cav { color:var(--muted); margin:10px 0 0; font-size:11.5px;
    line-height:1.45; }
  .leaflet-control-attribution { font-size:10px!important; }

  @media (max-width:860px) {
    .app { flex-direction:column; }
    .sidebar { width:100%; border-right:0; border-top:1px solid var(--line);
      order:2; max-height:56vh; }
    .mapwrap { order:1; flex:1 1 44vh; min-height:210px; }
    .sidebar[data-collapsed="true"] .figures,
    .sidebar[data-collapsed="true"] .period,
    .sidebar[data-collapsed="true"] .controls,
    .sidebar[data-collapsed="true"] .key,
    .sidebar[data-collapsed="true"] .listwrap,
    .sidebar[data-collapsed="true"] .foot,
    .sidebar[data-collapsed="true"] .warn { display:none; }
    .toggle { display:block; background:var(--paper); border:1px solid var(--line);
      border-radius:8px; padding:5px 11px; font-size:12px; cursor:pointer; }
    .head { display:flex; align-items:flex-start; justify-content:space-between;
      gap:12px; padding-bottom:12px; }
  }
</style>
</head>
<body>
<div class="app">
  <div class="mapwrap"><div id="map"></div></div>

  <aside class="sidebar" id="sidebar">
    <div class="head">
      <div>
        <h1>
          <svg width="19" height="19" viewBox="0 0 32 32" aria-hidden="true">
            <circle cx="16" cy="16" r="14" fill="none" stroke="#166534" stroke-width="2.5"/>
            <circle cx="16" cy="16" r="5.5" fill="#166534"/>
          </svg>
          Vanachakshu
        </h1>
        <div class="sub" id="sub">Possible forest disturbance</div>
      </div>
      <button class="toggle" id="toggle" aria-expanded="true">Hide</button>
    </div>

    <div class="warn">
      <strong>Not evidence of any offence.</strong> Automated satellite detections
      requiring ground verification. Clearing may be lawful.
    </div>

    <div class="figures">
      <div class="fig"><b id="s-count">0</b><span>detections</span></div>
      <div class="fig"><b id="s-area">0</b><span>hectares</span></div>
    </div>
    <div class="period" id="s-period"></div>

    <div class="controls">
      <div class="seg" role="group" aria-label="Filter by status">
        <button data-filter="all" aria-pressed="true">All
          <span class="n" id="n-all"></span></button>
        <button data-filter="confirmed" aria-pressed="false">Confirmed
          <span class="n" id="n-con"></span></button>
        <button data-filter="unconfirmed" aria-pressed="false">Pending
          <span class="n" id="n-pen"></span></button>
      </div>
      <select id="sort" aria-label="Sort detections">
        <option value="area-desc">Largest</option>
        <option value="area-asc">Smallest</option>
      </select>
    </div>

    <div class="key">
      <span><i class="ring" style="background:#be123c"></i>confirmed</span>
      <span><i style="background:#c2660a"></i>awaiting confirmation</span>
      <span><i class="box"></i>monitored area</span>
    </div>

    <div class="listwrap"><div id="list"></div></div>

    <div class="foot">
      <button class="dl" id="download">&darr;&nbsp; Download GeoJSON</button>

      <details open>
        <summary>How accurate is this?</summary>
        <p><strong>About 4 in 5 markers are real clearing</strong> (precision 0.80,
        95% CI 0.53&ndash;0.97, measured at 10&nbsp;m against Hansen Global Forest
        Change).</p>
        <p><strong>About 2 in 3 real clearings are missing.</strong> Recall is 0.32.
        An area with no marker has <em>not</em> been shown to be undisturbed &mdash;
        this map cannot be used as evidence that nothing happened.</p>
        <p>Outside the dashed boundary nothing is monitored at all.</p>
        <p>Detections lag by roughly a year: the underlying imagery is annual and
        published months after the year it covers. This is a record, not a
        real-time alarm.</p>
      </details>

      <details>
        <summary>What it is</summary>
        <p>India has no active near-real-time deforestation alert system. RADD does
        not cover India; the Forest Survey of India's <em>Anavaran</em> portal
        stopped updating in November 2025.</p>
        <p>Built on free data only.
        <a href="https://github.com/ChaitanyaKhanna14/vanachakshu">Source, method
        and measured limits</a>.</p>
        <p id="built"></p>
      </details>
    </div>
  </aside>
</div>

<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
<script>
const CFG = __VANACHAKSHU_CONFIG__;
const FEATURES = CFG.alerts.features;

const isConfirmed = p => (p.confirmations || 0) > 1;
const fmtHa = v => (v ?? 0).toFixed(2);

// Tile requests are what cost frames here, not the fifteen markers. Two full
// tile grids issue hundreds of HTTPS requests per pan, and every option below
// exists to reduce that count rather than to make each request faster.
const TILE_OPTS = {
  // Leaflet re-requests tiles continuously through a zoom gesture by default.
  // Waiting for the gesture to settle removes most of those requests, and the
  // stutter they cause with them.
  updateWhenZooming:false,
  // Default 2 loads two rings of off-screen tiles, per layer. One is plenty at
  // this screen size and cuts roughly half the requests.
  keepBuffer:1,
};

const map = L.map('map', {
  zoomControl:true,
  // Draw all markers into one canvas instead of one SVG node each. Marginal at
  // fifteen, but it also removes fifteen elements from hit-testing on hover.
  preferCanvas:true,
  // The tile cross-fade composites two full-screen tile grids every frame
  // while it runs. On integrated graphics that alone can halve the frame rate
  // during a pan, and it buys nothing but a fade.
  fadeAnimation:false,
});

// maxNativeZoom matters more than it looks. Past the depth a tile service
// actually publishes, Leaflet keeps requesting tiles that do not exist, and
// those failures retry. Capping it makes Leaflet upscale the deepest real tile
// instead — visually near-identical, and it ends the request storm at high
// zoom, which is exactly where this felt worst.
const imagery = L.tileLayer(CFG.imagery,
  { ...TILE_OPTS, maxZoom:19, maxNativeZoom:18, attribution:CFG.attribution });
const topo = L.tileLayer(CFG.topo,
  { ...TILE_OPTS, maxZoom:19, maxNativeZoom:17, attribution:CFG.attribution });
// Esri's imagery carries no labels, so a bare pin cannot answer the first
// question anyone asks of it. Reference tiles are cheap to skip mid-pan, so
// this one waits for the map to settle before loading at all.
const labels = L.tileLayer(CFG.labels,
  { ...TILE_OPTS, maxZoom:19, maxNativeZoom:16, opacity:.85, updateWhenIdle:true });

imagery.addTo(map);
labels.addTo(map);
L.control.layers({ 'Satellite':imagery, 'Topographic':topo },
  { 'Place names':labels }, { position:'topright' }).addTo(map);

// Topographic already has names baked in, so leaving the overlay on renders
// every label twice AND doubles the tile requests for no gain. Turning it off
// automatically must not overwrite a deliberate choice to hide it, hence the
// flag: without it, switching basemaps back and forth would silently re-enable
// labels the user had turned off.
let labelsWanted = true, programmatic = false;
function setLabels(on) {
  programmatic = true;
  if (on && !map.hasLayer(labels)) labels.addTo(map);
  if (!on && map.hasLayer(labels)) map.removeLayer(labels);
  programmatic = false;
}
map.on('overlayadd overlayremove', e => {
  if (!programmatic && e.layer === labels) labelsWanted = map.hasLayer(labels);
});
map.on('baselayerchange', e => setLabels(e.name !== 'Topographic' && labelsWanted));

L.control.scale({ imperial:false }).addTo(map);

// Recall is 0.32 and coverage is one taluk, so blank space is ambiguous:
// nothing found, or never looked at. Drawing the boundary separates the two.
const aoi = L.rectangle(
  [[CFG.bounds.south, CFG.bounds.west],[CFG.bounds.north, CFG.bounds.east]],
  { color:'#16a34a', weight:1.5, dashArray:'6 5', fill:false, interactive:false }
).addTo(map);

function popupHtml(p, ll) {
  const coords = ll.lat.toFixed(5) + ', ' + ll.lng.toFixed(5);
  return '<h3>Possible disturbance</h3>'
    + '<table>'
    + '<tr><td>Area</td><td>' + fmtHa(p.area_ha) + ' ha</td></tr>'
    + '<tr><td>Status</td><td>' + (isConfirmed(p) ? 'Confirmed across passes'
        : 'Awaiting confirmation') + '</td></tr>'
    + '<tr><td>First seen</td><td>' + (p.first_seen || '&mdash;') + '</td></tr>'
    + '<tr><td>Last seen</td><td>' + (p.last_seen || '&mdash;') + '</td></tr>'
    + '<tr><td>Location</td><td>' + coords + '</td></tr>'
    + '</table>'
    + '<a href="https://www.google.com/maps/search/?api=1&query=' + ll.lat + ',' + ll.lng
    + '" target="_blank" rel="noopener">Open in Google Maps</a>'
    + '<p class="cav">Requires ground verification. Clearing may be lawful.</p>';
}

const markers = new Map();
const rings = new Map();
const ringLayer = L.layerGroup().addTo(map);

const layer = L.geoJSON(CFG.alerts, {
  pointToLayer: (f, ll) => {
    const p = f.properties, c = isConfirmed(p);
    const r = Math.max(6, Math.min(15, 5 + Math.sqrt(p.area_ha ?? 0) * 7));
    // Every detection is solid and legible. An earlier version drew pending as
    // a faint hollow ring, and since every alert in the store is pending until
    // a second pass sees it, that made 100% of the map nearly invisible.
    const m = L.circleMarker(ll, {
      radius:r, color:'#ffffff', weight:2,
      fillColor: c ? '#be123c' : '#c2660a', fillOpacity:.9,
    });
    // Status carried by a separate halo rather than by fading the marker, so it
    // survives greyscale printing and red-green colour blindness.
    if (c) {
      const ring = L.circleMarker(ll, {
        radius:r + 4, color:'#be123c', weight:2, opacity:.75, fill:false,
      });
      rings.set(p.alert_id, ring);
      ringLayer.addLayer(ring);
    }
    markers.set(p.alert_id, m);
    return m;
  },
  onEachFeature: (f, l) => {
    l.bindPopup(popupHtml(f.properties, l.getLatLng()));
    l.on('click', () => select(f.properties.alert_id, false));
  },
}).addTo(map);

if (FEATURES.length) map.fitBounds(layer.getBounds(), { padding:[70,70], maxZoom:14 });
else map.fitBounds(aoi.getBounds(), { padding:[30,30] });

let selected = null;
function select(id, fly = true) {
  selected = id;
  const m = markers.get(id);
  markers.forEach((mk, key) => mk.setStyle({ weight: key === id ? 4 : 2 }));
  if (m) {
    if (fly) map.flyTo(m.getLatLng(), Math.max(map.getZoom(), 15), { duration:.6 });
    m.openPopup();
    m.bringToFront();
  }
  document.querySelectorAll('.row').forEach(r =>
    r.setAttribute('aria-current', String(r.dataset.id === id)));
  // A shareable link to one detection. Guarded because replaceState throws a
  // SecurityError on file:// in some browsers, which would break the whole
  // handler when previewing the page locally.
  try { history.replaceState(null, '', '#' + id); } catch (e) { /* file:// */ }
}

let filter = 'all', sort = 'area-desc';

function visible() {
  const out = FEATURES.filter(f => {
    if (filter === 'confirmed') return isConfirmed(f.properties);
    if (filter === 'unconfirmed') return !isConfirmed(f.properties);
    return true;
  });
  const key = {
    'area-desc': (a,b) => (b.properties.area_ha||0) - (a.properties.area_ha||0),
    'area-asc':  (a,b) => (a.properties.area_ha||0) - (b.properties.area_ha||0),
  }[sort];
  return out.sort(key);
}

function render() {
  const rows = visible();
  const list = document.getElementById('list');
  const nCon = FEATURES.filter(f => isConfirmed(f.properties)).length;

  document.getElementById('s-count').textContent = rows.length;
  document.getElementById('s-area').textContent =
    rows.reduce((t,f) => t + (f.properties.area_ha||0), 0).toFixed(1);
  // Counts on the filter itself, so an empty result is explained before it is
  // clicked rather than after.
  document.getElementById('n-all').textContent = FEATURES.length;
  document.getElementById('n-con').textContent = nCon;
  document.getElementById('n-pen').textContent = FEATURES.length - nCon;

  // When the detections do not record which years they compared, say when the
  // page was built instead. A plausible-looking wrong year is worse than an
  // obviously different fact, because nobody checks a wrong year.
  document.getElementById('s-period').textContent = CFG.period
    ? 'Imagery compared: ' + CFG.period
    : 'Imagery years not recorded for these detections \u00b7 page built ' + CFG.built;
  document.getElementById('sub').textContent =
    'Possible forest disturbance \u00b7 ' + CFG.aoiName;
  document.getElementById('built').textContent = 'Page built ' + CFG.built + '.';
  document.title = 'Vanachakshu \u2014 ' + CFG.aoiName;

  if (!rows.length) {
    list.innerHTML = '<div class="empty"><strong>Nothing matches this filter.</strong><br>'
      + (filter === 'confirmed'
          ? 'A detection becomes confirmed once a second pass sees it again. '
            + 'None have reached that yet.'
          : 'Recorded loss here is about 10 ha a year across 106,000 ha of forest, '
            + 'so an empty result is a normal outcome.')
      + '</div>';
    return;
  }

  list.innerHTML = '';
  for (const f of rows) {
    const p = f.properties, c = isConfirmed(p);
    const [lon, lat] = f.geometry.coordinates;
    const row = document.createElement('button');
    row.className = 'row';
    row.dataset.id = p.alert_id;
    row.setAttribute('aria-current', String(p.alert_id === selected));
    // Spans throughout: a <button> may only contain phrasing content, and the
    // earlier <div> inside it was invalid markup that assistive tech mishandles.
    row.innerHTML =
      '<span class="pip ' + (c ? 'c' : 'u') + '"></span>'
      + '<span class="main">'
      + '<span class="top"><span class="ha">' + fmtHa(p.area_ha) + ' ha</span>'
      + '<span class="badge ' + (c ? 'c' : 'u') + '">'
      + (c ? 'confirmed' : 'pending') + '</span></span>'
      + '<span class="meta">' + lat.toFixed(4) + ', ' + lon.toFixed(4)
      + ' \u00b7 ' + (p.last_seen || 'undated') + '</span>'
      + '</span>';
    row.addEventListener('click', () => select(p.alert_id));
    list.appendChild(row);
  }
}

document.querySelectorAll('.seg button').forEach(b => {
  b.addEventListener('click', () => {
    filter = b.dataset.filter;
    document.querySelectorAll('.seg button').forEach(o =>
      o.setAttribute('aria-pressed', String(o === b)));
    render();
  });
});
document.getElementById('sort').addEventListener('change', e => {
  sort = e.target.value; render();
});

// Principle 3 promised a downloadable file. Built from the inlined data, so it
// needs no server and cannot disagree with what is on screen.
document.getElementById('download').addEventListener('click', () => {
  const blob = new Blob([JSON.stringify(CFG.alerts, null, 2)],
    { type:'application/geo+json' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = 'vanachakshu-detections.geojson';
  a.click();
  URL.revokeObjectURL(a.href);
});

const toggle = document.getElementById('toggle');
toggle.addEventListener('click', () => {
  const sb = document.getElementById('sidebar');
  const hidden = sb.getAttribute('data-collapsed') === 'true';
  sb.setAttribute('data-collapsed', String(!hidden));
  toggle.textContent = hidden ? 'Hide' : 'Show';
  toggle.setAttribute('aria-expanded', String(hidden));
  map.invalidateSize();
});

render();
if (location.hash) select(location.hash.slice(1));
</script>
</body>
</html>
"""


def build_page(
    geojson: dict[str, Any],
    aoi_name: str,
    centre: tuple[float, float],
    min_area_ha: float | None = None,
    bounds: dict[str, float] | None = None,
) -> str:
    """Render the alert GeoJSON into one self-contained HTML page.

    ``min_area_ha`` filters to what the current configuration would emit. It is
    optional only so the renderer stays a pure function of its input; callers
    that publish should always pass it.

    ``bounds`` draws the monitored area. Without it the page cannot distinguish
    "looked at and found nothing" from "never looked at".

    The compared period is read out of the detections themselves rather than
    passed in or derived from the calendar — see :func:`compared_period`.
    """
    if min_area_ha is not None:
        geojson = meeting_current_config(geojson, min_area_ha)

    lon, lat = centre
    span = 0.15
    config = {
        "alerts": geojson,
        "aoiName": aoi_name,
        "period": compared_period(geojson),
        "built": datetime.now(UTC).strftime("%d %b %Y"),
        "imagery": _IMAGERY,
        "topo": _TOPO,
        "labels": _LABELS,
        "attribution": _ATTRIBUTION,
        "bounds": bounds
        or {"west": lon - span, "south": lat - span, "east": lon + span, "north": lat + span},
    }
    return _TEMPLATE.replace(_CONFIG_TOKEN, _as_js(config))


def write_page(
    geojson_path: Path,
    out_path: Path,
    aoi_name: str,
    centre: tuple[float, float],
    min_area_ha: float | None = None,
    bounds: dict[str, float] | None = None,
) -> tuple[Path, int, int]:
    """Read the alert GeoJSON and write the map page.

    Returns the path, how many detections were published, and how many were
    withheld as below ``min_area_ha`` — the caller reports the second number,
    because silently dropping three quarters of a map is not something that
    should happen without saying so.
    """
    geojson = json.loads(geojson_path.read_text(encoding="utf-8"))
    stored = len(geojson.get("features", []))

    published = geojson if min_area_ha is None else meeting_current_config(geojson, min_area_ha)
    shown = len(published["features"])

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(build_page(published, aoi_name, centre, bounds=bounds), encoding="utf-8")
    return out_path, shown, stored - shown
