"""Render the alert store as a single self-contained web page.

Design principle 4 says deliver where people already are, and principle 3 says
alerts must be actionable. A map is neither on its own — it is the thing someone
opens *after* an email, to decide whether a detection is worth a trip. That is
the job this page has to do well, and it is a different job from looking good.

Four things follow from it directly:

* **A list, not only pins.** Fifteen markers on satellite imagery cannot be
  scanned, sorted or counted by eye. The list is the part that makes this a tool.
* **Place names.** Esri's imagery carries no labels, so a bare pin cannot answer
  "where is this?" — the first question anyone asks. A reference overlay and a
  topographic basemap both answer it.
* **The monitored area, drawn.** Recall is 0.32 and coverage is one taluk, so a
  blank area can mean "nothing found", "not looked at closely enough", or "not
  monitored at all". Drawing the boundary separates the third from the others.
* **A download.** A forest officer wants coordinates in their GPS, not in a
  browser tab.

**Why not PMTiles.** The plan specified precomputed vector tiles. At this scale
that is engineering for a size that does not exist: the whole dataset inlines at
a few tens of kilobytes with no tile server and no second file to fall out of
sync. Revisit if the AOI grows a hundredfold.

**Why accuracy is on the page rather than in a footnote.** Roughly one in five
markers is wrong and two thirds of real clearing is missing. Someone who does
not know that will over-trust the pins and, worse, read empty space as safe.

The wording is deliberate throughout: *possible disturbance, requires ground
verification*. Never "illegal logging" — a model output is not evidence of a
crime, and the people most likely to be accused are rarely the people with the
means to contest it.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

__all__ = ["build_page", "meeting_current_config", "write_page"]

# Esri's free services. Attribution is a condition of use, not a courtesy.
_IMAGERY = (
    "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"
)
_TOPO = (
    "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}"
)
_LABELS = "https://server.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer/tile/{z}/{y}/{x}"
_ATTRIBUTION = (
    "Imagery &copy; Esri, Maxar, Earthstar Geographics &middot; "
    "Detections from Sentinel-2 and AlphaEarth via Google Earth Engine"
)

# Everything dynamic travels in one JSON object swapped in for this token. The
# alternative — str.format over the whole document — would mean doubling every
# CSS brace and would collide with JavaScript template literals, which is a lot
# of fragile escaping to save one substitution.
_CONFIG_TOKEN = "__VANACHAKSHU_CONFIG__"


def _as_js(value: Any) -> str:
    """Serialise a value for embedding inside a ``<script>`` element.

    ``json.dumps`` alone is **not** safe here. It escapes quotes but leaves
    ``<`` alone, so a property containing ``</script>`` ends the script element
    early and everything after it is parsed as markup — the classic way an
    inlined-JSON page becomes an injection vector.

    The alert data is generated by this pipeline rather than submitted by
    anyone, so nothing hostile is expected in it. That is a reason the bug would
    go unnoticed, not a reason it is safe: place names and future fields flow
    into this page, and the page is published.

    Escaping the angle brackets as ``\\u003c`` keeps the value identical after
    ``JSON.parse``. The line separators are escaped because they are valid in
    JSON but terminate a JavaScript string literal.
    """
    return (
        json.dumps(value, separators=(",", ":"))
        .replace("<", "\\u003c")
        .replace(">", "\\u003e")
        # Written as escapes rather than literals: the raw characters are
        # invisible in an editor, which is exactly how they survive review.
        .replace("\u2028", "\\u2028")
        .replace("\u2029", "\\u2029")
    )


def meeting_current_config(geojson: dict[str, Any], min_area_ha: float) -> dict[str, Any]:
    """Drop detections the current configuration would no longer produce.

    The alert store accumulates across runs, so it outlives the settings that
    filled it. When ``min_clearing_ha`` moved from 0.05 to 0.20 — a change that
    took measured precision from 0.31 to 0.80 — **42 of the 57 stored alerts
    were below the new floor**. Publishing them beside a claim of 0.80 precision
    overstated accuracy on three quarters of the map.

    Filtering here rather than pruning the store is deliberate: the store keeps
    its full history, and the page shows only what today's detector stands
    behind.
    """
    kept = [
        f
        for f in geojson.get("features", [])
        if float(f.get("properties", {}).get("area_ha") or 0.0) >= min_area_ha
    ]
    return {**geojson, "features": kept}


def compared_period(geojson: dict[str, Any]) -> str | None:
    """Which years of imagery the published detections were made from.

    Read out of the detections rather than from the calendar. An earlier version
    computed this from today's date and displayed **"2025→2026" for detections
    actually made from 2024 and 2025 imagery** — AlphaEarth is annual and
    published months in arrears, so the current year is never the compared year.
    On a page whose whole purpose is to be honest about its limits, inventing
    the data's date is close to the worst small lie available.

    Returns ``None`` when the detections do not record it, which is true of
    every alert written before the field existed. The page then shows its build
    date instead, clearly labelled as such. Showing nothing is better than
    showing a plausible wrong year, because a wrong year is not obviously wrong.
    """
    years: list[tuple[int, int]] = [
        (int(b), int(r))
        for f in geojson.get("features", [])
        if (b := f.get("properties", {}).get("baseline_year")) is not None
        and (r := f.get("properties", {}).get("recent_year")) is not None
    ]
    if not years:
        return None

    # Span the whole set: a store filled over several cycles can hold more than
    # one year-pair, and quoting only the newest would overstate how current the
    # older markers are.
    return f"{min(b for b, _ in years)}\u2013{max(r for _, r in years)}"


_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Vanachakshu &mdash; possible forest disturbance</title>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css">
<style>
  :root {
    --bg:#0d100e; --panel:#161b18; --raised:#1e2521; --ink:#e9efea; --muted:#93a29a;
    --line:#2a332e; --accent:#4ade80; --warn:#f5b638; --alert:#ff6a45; --focus:#7dd3fc;
    --pad:16px;
  }
  * { box-sizing:border-box; }
  html,body { margin:0; height:100%; background:var(--bg); color:var(--ink);
    font:15px/1.55 ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;
    -webkit-font-smoothing:antialiased; }
  button,select,input { font:inherit; color:inherit; }

  .app { display:flex; height:100%; }
  .sidebar { width:380px; flex:none; background:var(--panel); border-right:1px solid var(--line);
    display:flex; flex-direction:column; min-height:0; }
  .mapwrap { flex:1; position:relative; min-width:0; }
  #map { position:absolute; inset:0; background:#0a0c0b; }

  .head { padding:var(--pad); border-bottom:1px solid var(--line); }
  .head h1 { margin:0; font-size:19px; letter-spacing:-.02em; display:flex;
    align-items:center; gap:8px; }
  .head h1 svg { flex:none; }
  .head .sub { color:var(--muted); font-size:13px; margin-top:2px; }

  .warn { margin:var(--pad) var(--pad) 0; background:rgba(245,182,56,.09);
    border-left:3px solid var(--warn); padding:9px 11px; border-radius:0 6px 6px 0;
    font-size:12.5px; line-height:1.45; }

  .stats { display:grid; grid-template-columns:repeat(3,1fr); gap:1px; margin:var(--pad);
    background:var(--line); border:1px solid var(--line); border-radius:8px;
    overflow:hidden; }
  .stat { background:var(--raised); padding:9px 11px; }
  .stat b { display:block; font-size:19px; line-height:1.15; font-variant-numeric:tabular-nums; }
  .stat span { color:var(--muted); font-size:10.5px; text-transform:uppercase;
    letter-spacing:.05em; }

  .controls { padding:0 var(--pad) 10px; display:flex; gap:8px; align-items:center; }
  .seg { display:flex; background:var(--raised); border:1px solid var(--line);
    border-radius:7px; overflow:hidden; flex:1; }
  .seg button { flex:1; background:none; border:0; padding:6px 4px; font-size:12px;
    color:var(--muted); cursor:pointer; }
  .seg button[aria-pressed="true"] { background:var(--line); color:var(--ink); }
  select { background:var(--raised); border:1px solid var(--line); border-radius:7px;
    padding:6px 8px; font-size:12px; cursor:pointer; }

  .listwrap { flex:1; overflow-y:auto; min-height:0; border-top:1px solid var(--line); }
  .row { display:flex; gap:10px; align-items:flex-start; width:100%; text-align:left;
    background:none; border:0; border-bottom:1px solid var(--line); padding:10px var(--pad);
    cursor:pointer; }
  .row:hover { background:var(--raised); }
  .row[aria-current="true"] { background:var(--raised); box-shadow:inset 3px 0 0 var(--focus); }
  .row:focus-visible { outline:2px solid var(--focus); outline-offset:-2px; }
  .pip { flex:none; width:11px; height:11px; border-radius:50%; margin-top:5px; }
  .pip.c { background:var(--alert); border:2px solid var(--alert); }
  .pip.u { background:transparent; border:2px dashed var(--warn); }
  .row .main { flex:1; min-width:0; }
  .row .ha { font-variant-numeric:tabular-nums; font-weight:600; }
  .row .meta { color:var(--muted); font-size:11.5px; font-variant-numeric:tabular-nums;
    white-space:nowrap; overflow:hidden; text-overflow:ellipsis; }
  .row .tag { font-size:10px; text-transform:uppercase; letter-spacing:.05em;
    color:var(--muted); }
  .empty { padding:var(--pad); color:var(--muted); font-size:13px; }

  .foot { border-top:1px solid var(--line); padding:10px var(--pad) var(--pad); }
  .dl { width:100%; background:var(--raised); border:1px solid var(--line); color:var(--ink);
    border-radius:7px; padding:9px; cursor:pointer; font-size:13px; margin-bottom:10px; }
  .dl:hover { border-color:var(--accent); color:var(--accent); }
  details { font-size:12.5px; color:var(--muted); border-top:1px solid var(--line);
    padding-top:9px; margin-top:9px; }
  details:first-of-type { border-top:0; margin-top:0; }
  summary { cursor:pointer; color:var(--ink); font-size:12.5px; }
  details p { margin:8px 0; }
  a { color:var(--focus); }

  .legend { position:absolute; bottom:26px; left:12px; z-index:500; background:rgba(13,16,14,.86);
    backdrop-filter:blur(6px); border:1px solid var(--line); border-radius:8px;
    padding:9px 11px; font-size:11.5px; color:var(--muted); }
  .legend div { display:flex; align-items:center; gap:7px; margin:3px 0; }
  .legend i { width:11px; height:11px; border-radius:50%; flex:none; }
  .legend .box { width:13px; height:9px; border:1.5px dashed var(--accent); border-radius:2px; }

  .toggle { display:none; }

  .leaflet-popup-content-wrapper { background:var(--panel); color:var(--ink); border-radius:9px;
    border:1px solid var(--line); }
  .leaflet-popup-tip { background:var(--panel); }
  .leaflet-popup-content { margin:13px 15px; font-size:13px; }
  .leaflet-popup-content h3 { margin:0 0 7px; font-size:14px; }
  .leaflet-popup-content table { border-collapse:collapse; margin:7px 0; }
  .leaflet-popup-content td { padding:1.5px 12px 1.5px 0; }
  .leaflet-popup-content td:first-child { color:var(--muted); }
  .leaflet-popup-content .cav { color:var(--muted); margin:9px 0 0; font-size:11.5px; }
  .leaflet-container a.leaflet-popup-close-button { color:var(--muted); }
  .leaflet-control-attribution { background:rgba(13,16,14,.8)!important;
    color:var(--muted)!important; }
  .leaflet-control-attribution a { color:var(--muted)!important; }

  @media (max-width:820px) {
    .app { flex-direction:column; }
    .sidebar { width:100%; border-right:0; border-top:1px solid var(--line);
      order:2; max-height:52vh; }
    .mapwrap { order:1; flex:1 1 48vh; min-height:220px; }
    .sidebar[data-collapsed="true"] .stats,
    .sidebar[data-collapsed="true"] .controls,
    .sidebar[data-collapsed="true"] .listwrap,
    .sidebar[data-collapsed="true"] .foot,
    .sidebar[data-collapsed="true"] .warn { display:none; }
    .toggle { display:block; background:var(--raised); border:1px solid var(--line);
      border-radius:7px; padding:4px 10px; font-size:12px; cursor:pointer; }
    .head { display:flex; align-items:flex-start; justify-content:space-between; gap:10px; }
    .legend { display:none; }
  }
</style>
</head>
<body>
<div class="app">
  <div class="mapwrap">
    <div id="map"></div>
    <div class="legend">
      <div><i style="background:var(--alert);border:2px solid var(--alert)"></i>
        confirmed across passes</div>
      <div><i style="border:2px dashed var(--warn)"></i>awaiting confirmation</div>
      <div><span class="box"></span>monitored area</div>
    </div>
  </div>

  <aside class="sidebar" id="sidebar">
    <div class="head">
      <div>
        <h1>
          <svg width="17" height="17" viewBox="0 0 24 24" fill="none" aria-hidden="true">
            <circle cx="12" cy="12" r="9" stroke="#4ade80" stroke-width="2"/>
            <circle cx="12" cy="12" r="3.2" fill="#4ade80"/>
          </svg>
          Vanachakshu
        </h1>
        <div class="sub" id="sub">Possible forest disturbance</div>
      </div>
      <button class="toggle" id="toggle" aria-expanded="true">Hide</button>
    </div>

    <div class="warn">
      <strong>Not evidence of any offence.</strong> Automated satellite detections
      requiring ground verification. Clearing may be lawful.
    </div>

    <div class="stats">
      <div class="stat"><b id="s-count">0</b><span>detections</span></div>
      <div class="stat"><b id="s-area">0</b><span>hectares</span></div>
      <div class="stat"><b id="s-period">&mdash;</b><span id="s-period-label">compared</span></div>
    </div>

    <div class="controls">
      <div class="seg" role="group" aria-label="Filter by status">
        <button data-filter="all" aria-pressed="true">All</button>
        <button data-filter="confirmed" aria-pressed="false">Confirmed</button>
        <button data-filter="unconfirmed" aria-pressed="false">Pending</button>
      </div>
      <select id="sort" aria-label="Sort detections">
        <option value="area-desc">Largest</option>
        <option value="area-asc">Smallest</option>
        <option value="date-desc">Newest</option>
      </select>
    </div>

    <div class="listwrap"><div id="list"></div></div>

    <div class="foot">
      <button class="dl" id="download">&darr; Download GeoJSON</button>

      <details open>
        <summary>How accurate is this?</summary>
        <p><strong>About 4 in 5 markers are real clearing</strong> (precision 0.80,
        95% CI 0.53&ndash;0.97, measured at 10&nbsp;m against Hansen Global Forest
        Change).</p>
        <p><strong>About 2 in 3 real clearings are missing.</strong> Recall is 0.32.
        An area with no marker has <em>not</em> been shown to be undisturbed &mdash;
        this map cannot be used as evidence that nothing happened.</p>
        <p>Outside the dashed boundary nothing is monitored at all.</p>
        <p>Detections lag by roughly a year: the underlying imagery is annual and
        published months after the year it covers. This is a record, not a
        real-time alarm.</p>
      </details>

      <details>
        <summary>What it is</summary>
        <p>India has no active near-real-time deforestation alert system. RADD does
        not cover India; the Forest Survey of India's <em>Anavaran</em> portal
        stopped updating in November 2025.</p>
        <p>Built on free data only.
        <a href="https://github.com/ChaitanyaKhanna14/vanachakshu">Source, method
        and measured limits</a>.</p>
        <p id="built"></p>
      </details>
    </div>
  </aside>
</div>

<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
<script>
const CFG = __VANACHAKSHU_CONFIG__;
const FEATURES = CFG.alerts.features;

const isConfirmed = p => (p.confirmations || 0) > 1;
const fmtHa = v => (v ?? 0).toFixed(2);

const map = L.map('map', { zoomControl:true, attributionControl:true });
const imagery = L.tileLayer(CFG.imagery, { maxZoom:19, attribution:CFG.attribution });
const topo = L.tileLayer(CFG.topo, { maxZoom:19, attribution:CFG.attribution });
imagery.addTo(map);
// Place names on their own layer: Esri's imagery carries none, and a pin with
// no nearby name cannot answer the first question anyone asks of it.
L.tileLayer(CFG.labels, { maxZoom:19, opacity:.9 }).addTo(map);
L.control.layers({ 'Satellite':imagery, 'Topographic':topo }, null,
  { position:'topright' }).addTo(map);
L.control.scale({ imperial:false }).addTo(map);

// Recall is 0.32 and coverage is one taluk, so blank space is ambiguous:
// nothing found, or never looked at. Drawing the boundary separates the two.
const aoi = L.rectangle(
  [[CFG.bounds.south, CFG.bounds.west],[CFG.bounds.north, CFG.bounds.east]],
  { color:'#4ade80', weight:1.5, dashArray:'6 5', fill:false, interactive:false }
).addTo(map);

function popupHtml(p, ll) {
  const coords = ll.lat.toFixed(5) + ', ' + ll.lng.toFixed(5);
  return '<h3>Possible disturbance</h3>'
    + '<table>'
    + '<tr><td>Area</td><td>' + fmtHa(p.area_ha) + ' ha</td></tr>'
    + '<tr><td>Status</td><td>' + (isConfirmed(p) ? 'Confirmed across passes'
        : 'Awaiting confirmation') + '</td></tr>'
    + '<tr><td>First seen</td><td>' + (p.first_seen || '&mdash;') + '</td></tr>'
    + '<tr><td>Last seen</td><td>' + (p.last_seen || '&mdash;') + '</td></tr>'
    + '<tr><td>Location</td><td>' + coords + '</td></tr>'
    + '</table>'
    + '<a href="https://www.google.com/maps/search/?api=1&query=' + ll.lat + ',' + ll.lng
    + '" target="_blank" rel="noopener">Open in Google Maps</a>'
    + '<p class="cav">Requires ground verification. Clearing may be lawful.</p>';
}

const markers = new Map();
const layer = L.geoJSON(CFG.alerts, {
  pointToLayer: (f, ll) => {
    const p = f.properties, c = isConfirmed(p);
    // Confirmed and pending differ by FILL and DASH, not only by hue: about 8%
    // of men cannot separate the orange from the red reliably.
    const m = L.circleMarker(ll, {
      radius: Math.max(6, Math.min(15, 5 + Math.sqrt(p.area_ha ?? 0) * 7)),
      color: c ? '#ff6a45' : '#f5b638',
      weight: 2,
      dashArray: c ? null : '3 3',
      fillOpacity: c ? .5 : .08,
    });
    markers.set(p.alert_id, m);
    return m;
  },
  onEachFeature: (f, l) => {
    l.bindPopup(popupHtml(f.properties, l.getLatLng()));
    l.on('click', () => select(f.properties.alert_id, false));
  },
}).addTo(map);

if (FEATURES.length) map.fitBounds(layer.getBounds(), { padding:[70,70], maxZoom:14 });
else map.fitBounds(aoi.getBounds(), { padding:[30,30] });

let selected = null;
function select(id, fly = true) {
  selected = id;
  const m = markers.get(id);
  markers.forEach((mk, key) => mk.setStyle({ weight: key === id ? 4 : 2 }));
  if (m) {
    if (fly) map.flyTo(m.getLatLng(), Math.max(map.getZoom(), 15), { duration:.6 });
    m.openPopup();
    m.bringToFront();
  }
  document.querySelectorAll('.row').forEach(r =>
    r.setAttribute('aria-current', String(r.dataset.id === id)));
  // A shareable link to one detection. Without it the only way to point someone
  // at a specific marker is to describe where it is.
  history.replaceState(null, '', '#' + id);
}

let filter = 'all', sort = 'area-desc';

function visible() {
  let out = FEATURES.filter(f => {
    if (filter === 'confirmed') return isConfirmed(f.properties);
    if (filter === 'unconfirmed') return !isConfirmed(f.properties);
    return true;
  });
  const key = {
    'area-desc': (a,b) => (b.properties.area_ha||0) - (a.properties.area_ha||0),
    'area-asc':  (a,b) => (a.properties.area_ha||0) - (b.properties.area_ha||0),
    'date-desc': (a,b) => String(b.properties.last_seen||'').localeCompare(
                          String(a.properties.last_seen||'')),
  }[sort];
  return out.sort(key);
}

function render() {
  const rows = visible();
  const list = document.getElementById('list');

  document.getElementById('s-count').textContent = rows.length;
  document.getElementById('s-area').textContent =
    rows.reduce((t,f) => t + (f.properties.area_ha||0), 0).toFixed(1);
  // When the detections do not record which years they compared, show the
  // build date and say so. A plausible-looking wrong year is worse than an
  // obviously different fact, because nobody checks a wrong year.
  document.getElementById('s-period').textContent = CFG.period || CFG.built.split(' ')[1];
  document.getElementById('s-period-label').textContent =
    CFG.period ? 'imagery years' : 'page built';
  document.getElementById('sub').textContent =
    'Possible forest disturbance \\u00b7 ' + CFG.aoiName;
  document.getElementById('built').textContent = 'Page built ' + CFG.built + '.';

  if (!rows.length) {
    list.innerHTML = '<div class="empty">No detections match this filter. '
      + 'That is a normal result &mdash; recorded loss here is about 10 ha a year '
      + 'across 106,000 ha of forest.</div>';
    return;
  }

  list.innerHTML = '';
  for (const f of rows) {
    const p = f.properties, c = isConfirmed(p);
    const [lon, lat] = f.geometry.coordinates;
    const row = document.createElement('button');
    row.className = 'row';
    row.dataset.id = p.alert_id;
    row.setAttribute('aria-current', String(p.alert_id === selected));
    row.innerHTML =
      '<span class="pip ' + (c ? 'c' : 'u') + '"></span>'
      + '<span class="main">'
      + '<span class="ha">' + fmtHa(p.area_ha) + ' ha</span> '
      + '<span class="tag">' + (c ? 'confirmed' : 'pending') + '</span>'
      + '<div class="meta">' + lat.toFixed(4) + ', ' + lon.toFixed(4)
      + ' \\u00b7 ' + (p.last_seen || 'undated') + '</div>'
      + '</span>';
    row.addEventListener('click', () => select(p.alert_id));
    list.appendChild(row);
  }
}

document.querySelectorAll('.seg button').forEach(b => {
  b.addEventListener('click', () => {
    filter = b.dataset.filter;
    document.querySelectorAll('.seg button').forEach(o =>
      o.setAttribute('aria-pressed', String(o === b)));
    render();
  });
});
document.getElementById('sort').addEventListener('change', e => {
  sort = e.target.value; render();
});

// Principle 3 promised a downloadable file. Built from the inlined data, so it
// needs no server and cannot disagree with what is on screen.
document.getElementById('download').addEventListener('click', () => {
  const blob = new Blob([JSON.stringify(CFG.alerts, null, 2)],
    { type:'application/geo+json' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = 'vanachakshu-detections.geojson';
  a.click();
  URL.revokeObjectURL(a.href);
});

const toggle = document.getElementById('toggle');
toggle.addEventListener('click', () => {
  const sb = document.getElementById('sidebar');
  const hidden = sb.getAttribute('data-collapsed') === 'true';
  sb.setAttribute('data-collapsed', String(!hidden));
  toggle.textContent = hidden ? 'Hide' : 'Show';
  toggle.setAttribute('aria-expanded', String(hidden));
  map.invalidateSize();
});

render();
if (location.hash) select(location.hash.slice(1));
</script>
</body>
</html>
"""


def build_page(
    geojson: dict[str, Any],
    aoi_name: str,
    centre: tuple[float, float],
    min_area_ha: float | None = None,
    bounds: dict[str, float] | None = None,
) -> str:
    """Render the alert GeoJSON into one self-contained HTML page.

    ``min_area_ha`` filters to what the current configuration would emit. It is
    optional only so the renderer stays a pure function of its input; callers
    that publish should always pass it.

    ``bounds`` draws the monitored area. Without it the page cannot distinguish
    "looked at and found nothing" from "never looked at".

    The compared period is read out of the detections themselves rather than
    passed in or derived from the calendar — see :func:`compared_period`.
    """
    if min_area_ha is not None:
        geojson = meeting_current_config(geojson, min_area_ha)

    lon, lat = centre
    span = 0.15
    config = {
        "alerts": geojson,
        "aoiName": aoi_name,
        "period": compared_period(geojson),
        "built": datetime.now(UTC).strftime("%d %b %Y"),
        "imagery": _IMAGERY,
        "topo": _TOPO,
        "labels": _LABELS,
        "attribution": _ATTRIBUTION,
        "bounds": bounds
        or {"west": lon - span, "south": lat - span, "east": lon + span, "north": lat + span},
    }
    return _TEMPLATE.replace(_CONFIG_TOKEN, _as_js(config))


def write_page(
    geojson_path: Path,
    out_path: Path,
    aoi_name: str,
    centre: tuple[float, float],
    min_area_ha: float | None = None,
    bounds: dict[str, float] | None = None,
) -> tuple[Path, int, int]:
    """Read the alert GeoJSON and write the map page.

    Returns the path, how many detections were published, and how many were
    withheld as below ``min_area_ha`` — the caller reports the second number,
    because silently dropping three quarters of a map is not something that
    should happen without saying so.
    """
    geojson = json.loads(geojson_path.read_text(encoding="utf-8"))
    stored = len(geojson.get("features", []))

    published = geojson if min_area_ha is None else meeting_current_config(geojson, min_area_ha)
    shown = len(published["features"])

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(build_page(published, aoi_name, centre, bounds=bounds), encoding="utf-8")
    return out_path, shown, stored - shown
