"""Render the alert store as a single self-contained web page.

Design principle 4 says deliver where people already are, and principle 3 says
alerts must be actionable. A map is neither of those on its own — it is the
thing someone opens *after* an email, to see where the detection actually is and
decide whether it is worth a trip. That is the job this page has to do well.

**Why not PMTiles.** The original plan specified precomputed vector tiles. At 57
alerts that is engineering for a scale that does not exist: the entire dataset
inlines into the HTML at a few tens of kilobytes and renders instantly, with no
tile server, no build step and no second file to keep in sync. Revisit if the
AOI grows by two orders of magnitude.

**Why the accuracy is on the page and not in a footnote.** Roughly one in five
markers is wrong and about two thirds of real clearing is missing entirely.
Someone who does not know that will over-trust the dots and, worse, read empty
areas as safe. Publishing the number where it cannot be missed is the difference
between a useful tool and a misleading one.

The wording is deliberate throughout: *possible disturbance, requires ground
verification*. Never "illegal logging" — a model output is not evidence of a
crime, and the people most likely to be accused are rarely the people with the
means to contest it.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

__all__ = ["build_page", "write_page"]


def _as_js(value: Any) -> str:
    """Serialise a value for embedding inside a ``<script>`` element.

    ``json.dumps`` alone is **not** safe here. It escapes quotes but leaves
    ``<`` and ``/`` alone, so a property containing ``</script>`` ends the
    script element early and everything after it is parsed as markup — the
    classic way an inlined-JSON page becomes an injection vector.

    The alert data is generated by this pipeline rather than submitted by
    anyone, so nothing hostile is expected in it. That is a reason the bug
    would go unnoticed, not a reason it is safe: place names and future fields
    flow into this page, and the page is published.

    Escaping the angle brackets as ``\\u003c`` keeps the value identical after
    ``JSON.parse`` while making it impossible to close the element. The line
    separators are escaped because they are valid in JSON but terminate a
    JavaScript string literal.
    """
    return (
        json.dumps(value, separators=(",", ":"))
        .replace("<", "\\u003c")
        .replace(">", "\\u003e")
        .replace("\u2028", "\\u2028")
        .replace("\u2029", "\\u2029")
    )


# Esri's free imagery service. Attribution is a condition of use, not a courtesy.
_BASEMAP = (
    "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"
)
_ATTRIBUTION = (
    "Imagery &copy; Esri, Maxar, Earthstar Geographics &middot; "
    "Detections from Sentinel-1/2 via Google Earth Engine"
)

_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Vanachakshu &mdash; possible forest disturbance, {aoi_name}</title>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css">
<style>
  :root {{
    --bg: #0f1210; --panel: #191e1b; --ink: #e8ede9; --muted: #9aa8a0;
    --line: #2b332e; --warn: #f0b429; --alert: #ff6b4a; --ok: #4ade80;
  }}
  * {{ box-sizing: border-box; }}
  html, body {{ margin: 0; height: 100%; background: var(--bg); color: var(--ink);
    font: 15px/1.5 ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif; }}
  #map {{ position: absolute; inset: 0; }}
  .panel {{
    position: absolute; top: 12px; left: 12px; z-index: 1000; width: min(340px, calc(100vw - 24px));
    background: var(--panel); border: 1px solid var(--line); border-radius: 10px;
    padding: 14px 16px; box-shadow: 0 6px 24px rgba(0,0,0,.45); max-height: calc(100vh - 24px);
    overflow-y: auto;
  }}
  .panel h1 {{ margin: 0 0 2px; font-size: 17px; letter-spacing: -.01em; }}
  .panel .sub {{ color: var(--muted); font-size: 13px; margin-bottom: 10px; }}
  .warn {{
    background: rgba(240,180,41,.1); border-left: 3px solid var(--warn);
    padding: 8px 10px; border-radius: 4px; font-size: 13px; margin-bottom: 10px;
  }}
  .stats {{ display: flex; gap: 14px; margin-bottom: 10px; }}
  .stat b {{ display: block; font-size: 20px; line-height: 1.1; }}
  .stat span {{ color: var(--muted); font-size: 11px; text-transform: uppercase;
    letter-spacing: .04em; }}
  details {{ font-size: 13px; color: var(--muted); border-top: 1px solid var(--line);
    padding-top: 8px; }}
  details summary {{ cursor: pointer; color: var(--ink); font-size: 13px; }}
  details p {{ margin: 8px 0; }}
  .legend {{ display: flex; gap: 12px; font-size: 12px; color: var(--muted); margin: 8px 0; }}
  .dot {{ display: inline-block; width: 9px; height: 9px; border-radius: 50%;
    margin-right: 4px; vertical-align: middle; }}
  a {{ color: #7dd3fc; }}
  .leaflet-popup-content-wrapper {{ background: var(--panel); color: var(--ink);
    border-radius: 8px; }}
  .leaflet-popup-tip {{ background: var(--panel); }}
  .leaflet-popup-content {{ margin: 12px 14px; font-size: 13px; }}
  .leaflet-popup-content h3 {{ margin: 0 0 6px; font-size: 14px; }}
  .leaflet-popup-content table {{ border-collapse: collapse; margin: 6px 0; }}
  .leaflet-popup-content td {{ padding: 1px 10px 1px 0; }}
  .leaflet-popup-content td:first-child {{ color: var(--muted); }}
</style>
</head>
<body>
<div id="map"></div>
<div class="panel">
  <h1>Vanachakshu</h1>
  <div class="sub">Possible forest disturbance &middot; {aoi_name}</div>

  <div class="warn">
    <strong>Not evidence of any offence.</strong> These are automated satellite
    detections that require ground verification. Clearing may be lawful.
  </div>

  <div class="stats">
    <div class="stat"><b>{count}</b><span>detections</span></div>
    <div class="stat"><b>{total_ha}</b><span>hectares</span></div>
    <div class="stat"><b>{updated}</b><span>updated</span></div>
  </div>

  <div class="legend">
    <span><i class="dot" style="background:var(--alert)"></i>confirmed</span>
    <span><i class="dot" style="background:var(--warn)"></i>awaiting confirmation</span>
  </div>

  <details open>
    <summary>How accurate is this?</summary>
    <p><strong>About 4 in 5 markers are real clearing</strong>
    (precision 0.80, 95% CI 0.53&ndash;0.97, measured at 10&nbsp;m against Hansen
    Global Forest Change).</p>
    <p><strong>About 2 in 3 real clearings are missing.</strong> Recall is 0.32.
    An area with no marker has <em>not</em> been shown to be undisturbed &mdash;
    this map cannot be used as evidence that nothing happened.</p>
    <p>Detections lag by roughly a year: the underlying annual imagery is
    published months after the year it covers. This is a record, not a
    real-time alarm.</p>
  </details>

  <details>
    <summary>What it is</summary>
    <p>India has no active near-real-time deforestation alert system. RADD does
    not cover India; the Forest Survey of India's <em>Anavaran</em> portal
    stopped updating in November 2025.</p>
    <p>Built on free data only &mdash; Sentinel-1, Sentinel-2 and AlphaEarth
    embeddings via Google Earth Engine.
    <a href="https://github.com/ChaitanyaKhanna14/vanachakshu">Source and
    method</a>.</p>
  </details>
</div>

<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
<script>
const ALERTS = {geojson};

const map = L.map('map', {{ zoomControl: true }}).setView([{lat}, {lon}], 11);
L.tileLayer({basemap}, {{ maxZoom: 19, attribution: {attribution} }}).addTo(map);
L.control.scale({{ imperial: false }}).addTo(map);

const confirmed = p => (p.confirmations || 0) > 1;

function popup(p, ll) {{
  const status = confirmed(p) ? 'Confirmed across passes' : 'Awaiting confirmation';
  // Coordinates to five decimals: about a metre, enough to navigate to and
  // short enough to read out over a phone.
  const coords = ll.lat.toFixed(5) + ', ' + ll.lng.toFixed(5);
  return `<h3>Possible disturbance</h3>
    <table>
      <tr><td>Area</td><td>${{(p.area_ha ?? 0).toFixed(2)}} ha</td></tr>
      <tr><td>Status</td><td>${{status}}</td></tr>
      <tr><td>First seen</td><td>${{p.first_seen ?? '&mdash;'}}</td></tr>
      <tr><td>Last seen</td><td>${{p.last_seen ?? '&mdash;'}}</td></tr>
      <tr><td>Location</td><td>${{coords}}</td></tr>
    </table>
    <a href="https://www.google.com/maps/search/?api=1&query=${{ll.lat}},${{ll.lng}}"
       target="_blank" rel="noopener">Open in Google Maps</a>
    <p style="color:var(--muted);margin:8px 0 0">Requires ground verification.
    Clearing may be lawful.</p>`;
}}

const layer = L.geoJSON(ALERTS, {{
  pointToLayer: (f, ll) => L.circleMarker(ll, {{
    // Radius tracks area so a 2 ha clearing does not look like a 0.05 ha one,
    // with a floor so the smallest detections stay clickable.
    radius: Math.max(5, Math.min(14, 4 + Math.sqrt(f.properties.area_ha ?? 0) * 6)),
    color: confirmed(f.properties) ? '#ff6b4a' : '#f0b429',
    weight: 2, fillOpacity: .25,
  }}),
  onEachFeature: (f, l) => l.bindPopup(popup(f.properties, l.getLatLng())),
}}).addTo(map);

if (ALERTS.features.length) map.fitBounds(layer.getBounds(), {{ padding: [60, 60] }});
</script>
</body>
</html>
"""


def build_page(geojson: dict[str, Any], aoi_name: str, centre: tuple[float, float]) -> str:
    """Render the alert GeoJSON into one self-contained HTML page."""
    features = geojson.get("features", [])
    total_ha = sum(float(f.get("properties", {}).get("area_ha") or 0.0) for f in features)
    lon, lat = centre

    return _TEMPLATE.format(
        aoi_name=aoi_name,
        count=len(features),
        total_ha=f"{total_ha:.1f}",
        updated=datetime.now(UTC).strftime("%d %b %Y"),
        # _as_js everywhere a value crosses into JavaScript, including the
        # plain strings: json.dumps alone would leave a "</script>" in the data
        # able to close the element early.
        geojson=_as_js(geojson),
        basemap=_as_js(_BASEMAP),
        attribution=_as_js(_ATTRIBUTION),
        lat=lat,
        lon=lon,
    )


def write_page(
    geojson_path: Path, out_path: Path, aoi_name: str, centre: tuple[float, float]
) -> Path:
    """Read the alert GeoJSON and write the map page beside it."""
    geojson = json.loads(geojson_path.read_text(encoding="utf-8"))
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(build_page(geojson, aoi_name, centre), encoding="utf-8")
    return out_path
